### ISSUE TITLE
s2p stuck without any output

### ISSUE THREAD

**Issue by daviddemeij** [MISS3D/s2p#211]
When trying to run S2P (the latest Github version), it just gets stuck for hours without giving any output.

I run the command: `s2p ../efs/stereo_image/config.json`

With the following config:
```
{
  "out_dir" : "/home/ubuntu/efs/stereo_image/s2p_output2",
  "images" : [
    { "img" :"image1.TIF",
      "rpc" : "image1.RPB"},
    { "img" : "image2.TIF",
      "rpc" : "image2.RPB"}
    ],
  "roi" : {
      "x" : 150,
      "y" : 150,
      "w" : 700,
      "h" : 700
  },
  "full_img" : false,
  "matching_algorithm" : "mgm",
  "horizontal_margin": 20,
  "vertical_margin": 5,
  "sift_match_thresh" : 0.6,
  "disp_range_extra_margin" : 0.2,
  "n_gcp_per_axis" : 5,
  "epipolar_thresh" : 0.5,
  "debug" : false,
  "temporary_dir" : "/tmp",
  "tile_size" : 300,
  "clean_tmp" : true,
  "clean_intermediate" : false,
  "fusion_thresh" : 3,
  "disp_range_method" : "sift",
  "msk_erosion": 0,
  "dsm_resolution": 0.5
}
```

Is S2P unable to use `.RPB` files? I did manage to start the process using the pip version of S2P, but then it crashed at a later stage.

The tests up and including `end2end_pair` are successful, but for the `end2end_triplet` test, I get the following error:

```
running stereo matching...
done 8 / 8 tiles
Elapsed time: 0:00:06.037232

computing height maps...
done 8 / 8 tiles
Elapsed time: 0:00:00.427099

computing local pairwise height offsets...
Elapsed time: 0:00:00.126665

computing global pairwise height offsets...
Traceback (most recent call last):
  File "tests/test_s2p.py", line 307, in <module>
    command(*args)
  File "tests/test_s2p.py", line 218, in end2end
    s2p.main(test_cfg)
  File "/home/ubuntu/s2p/s2p/__init__.py", line 711, in main
    global_mean_heights(tiles)
  File "/home/ubuntu/s2p/s2p/__init__.py", line 443, in global_mean_heights
    for t in tiles]
  File "/home/ubuntu/s2p/s2p/__init__.py", line 443, in <listcomp>
    for t in tiles]
  File "/home/ubuntu/miniconda2/envs/20tree/lib/python3.7/site-packages/numpy/lib/npyio.py", line 962, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/ubuntu/miniconda2/envs/20tree/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 266, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/ubuntu/miniconda2/envs/20tree/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 624, in open
    raise IOError("%s not found." % path)
OSError: /home/ubuntu/s2p/tests/data/input_triplet/../../testoutput/output_triplet/tiles/row_0000150_height_350/col_0000150_width_350/local_mean_heights.txt not found.
```

I also often get the following warnings:
```
WARNING: ignoring unknown parameter skip_existing.
WARNING: ignoring unknown parameter utm_bbx.
```

**Comment by daviddemeij** [comment]
update: when I add "utm_zone" to the config the process does start.

**Comment by daviddemeij** [comment]
Now I am getting the follow error (still letting it run, as I am not sure it is a critical error):
```
ubuntu@ip-172-31-14-131:~/efs/stereo_image$ s2p config.json 
tile size: 298 298
total number of tiles: 3025 (55 x 55)

discarding masked tiles...
done 3025 / 3025 tiles
Elapsed time: 0:00:00.724115

correcting pointing locally...
Timeout while running <multiprocessing.pool.ApplyResult object at 0x7f2465d6ec50>
Timeout while running <multiprocessing.pool.ApplyResult object at 0x7f2465d6ecf8>
Timeout while running <multiprocessing.pool.ApplyResult object at 0x7f2465d6eda0>
Timeout while running <multiprocessing.pool.ApplyResult object at 0x7f2465d6ee48>

```

**Comment by lionlai1989** [comment]
It happened to me once. If I remember correctly, I have to select the AOI with the smaller size which can bypass this issue. But I don't know the root cause of it.
