### ISSUE TITLE
input_pair Test Failure

### ISSUE THREAD

**Issue by mjstroud** [MISS3D/s2p#214]
I attempted to run a test using the "input_pair" config and data as installed by way of pip. I am getting the following error...

~/s2p/tests/data/input_pair# s2p config.json
Traceback (most recent call last):
  File "/usr/local/bin/s2p", line 11, in <module>
    load_entry_point('s2p==1.0b18', 'console_scripts', 's2p')()
  File "/usr/local/lib/python3.5/dist-packages/s2p/cli.py", line 22, in main
    s2p.main(user_cfg)
  File "/usr/local/lib/python3.5/dist-packages/s2p/__init__.py", line 568, in main
    initialization.build_cfg(user_cfg)
  File "/usr/local/lib/python3.5/dist-packages/s2p/initialization.py", line 113, in build_cfg
    check_parameters(user_cfg)
  File "/usr/local/lib/python3.5/dist-packages/s2p/initialization.py", line 58, in check_parameters
    img['rpc'] = rpcm.rpc_from_geotiff(img['img'])
  File "/usr/local/lib/python3.5/dist-packages/rpcm/rpc_model.py", line 70, in rpc_from_geotiff
    return RPCModel(rpc_dict)
  File "/usr/local/lib/python3.5/dist-packages/rpcm/rpc_model.py", line 93, in __init__
    self.row_offset = float(d['LINE_OFF'])
KeyError: 'LINE_OFF'

Installation ran without error, and the "input_triplet" test ran successfully, so I have no reason to believe that the installation is the cause. I am getting the same error for what is a more complicated test of my own, and I am trying to figure out what I need to fix to get past this issue.

**Comment by carlodef** [comment]
The version distributed on PyPI and installed by `pip` is the one from this other repository: https://github.com/cmla/s2p

You should clone that git repository and run the tests on the data provided there.

**Comment by mjstroud** [comment]
While this did fix the test, an attempt with my own images still yields the same error. I have tried with and without "rpc" files and I get the same result. Any thoughts



> 
> 
> The version distributed on PyPI and installed by `pip` is the one from this other repository: https://github.com/cmla/s2p
> 
> You should clone that git repository and run the tests on the data provided there.

**Comment by jun1215** [comment]
Hi, did you solved the problem above?
