### ISSUE TITLE
Error - exit status -6

### ISSUE THREAD

**Issue by MiladGhorbaniG** [MISS3D/s2p#223]
Hi, I'm using :
`
Ubuntu 16.04
Python 3.5
Gdal 2.2.2
`
I installed s2p and then ran the example in the description. I faced with the bellow error:

> sudo s2p tests/data/input_pair/config.json
> WARNING: out_dir is a relative path. It is interpreted with respect to tests/data/input_pair/config.json location (not cwd)
> out_dir is: /home/miladg/projects/Stereo_Satellite_Disparity/Geo-Alberta, Canada/s2p/tests/data/input_pair/../../testoutput/output_pair
> /usr/local/lib/python3.5/dist-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=' syntax is deprecated. '' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
>   return _prepare_from_string(" ".join(pjargs))
> /usr/local/lib/python3.5/dist-packages/pyproj/crs/crs.py:294: FutureWarning: '+init=' syntax is deprecated. '' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
>   projstring = _prepare_from_string(" ".join((projstring, projkwargs)))
> /usr/local/lib/python3.5/dist-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=' syntax is deprecated. '' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
>   return _prepare_from_string(" ".join(pjargs))
> /usr/local/lib/python3.5/dist-packages/pyproj/crs/crs.py:294: FutureWarning: '+init=' syntax is deprecated. '' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
>   projstring = _prepare_from_string(" ".join((projstring, projkwargs)))
> /usr/local/lib/python3.5/dist-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=' syntax is deprecated. '' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
>   return _prepare_from_string(" ".join(pjargs))
> /usr/local/lib/python3.5/dist-packages/pyproj/crs/crs.py:294: FutureWarning: '+init=' syntax is deprecated. '' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
>   projstring = _prepare_from_string(" ".join((projstring, projkwargs)))
> /usr/local/lib/python3.5/dist-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=' syntax is deprecated. '' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
>   return _prepare_from_string(" ".join(pjargs))
> /usr/local/lib/python3.5/dist-packages/pyproj/crs/crs.py:294: FutureWarning: '+init=' syntax is deprecated. '' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
>   projstring = _prepare_from_string(" ".join((projstring, projkwargs)))
> tile size: 350 350
> total number of tiles: 4 (2 x 2)
> 
> discarding masked tiles...
> done 4 / 4 tiles
> Elapsed time: 0:00:00.288161
> 
> correcting pointing locally...
> done 4 / 4 tiles
> Elapsed time: 0:00:03.675108
> 
> correcting pointing globally...
> Elapsed time: 0:00:00.004381
> 
> rectifying tiles...
> done 4 / 4 tiles
> Elapsed time: 0:00:00.433799
> 
> running stereo matching...
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
>     result = (True, func(*args, **kwds))
>   File "/usr/local/lib/python3.5/dist-packages/s2p/parallel.py", line 43, in tilewise_wrapper
>     out = fun(*args)
>   File "/usr/local/lib/python3.5/dist-packages/s2p/__init__.py", line 205, in stereo_matching
>     disp_max)
>   File "/usr/local/lib/python3.5/dist-packages/s2p/block_matching.py", line 182, in compute_disparity_map
>     timeout=timeout,
>   File "/usr/local/lib/python3.5/dist-packages/s2p/common.py", line 93, in run
>     env=env, timeout=timeout, check=True)
>   File "/usr/lib/python3.5/subprocess.py", line 708, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['mgm', '-r', '-16', '-R', '13', '-s', 'vfit', '-t', 'census', '-O', '8', '-confidence_consensusL', '/home/miladg/projects/Stereo_Satellite_Disparity/Geo-Alberta,', 'Canada/s2p/tests/data/input_pair/../../testoutput/output_pair/tiles/row_0000150_height_350/col_0000150_width_350/pair_1/rectified_disp_confidence.tif', '/home/miladg/projects/Stereo_Satellite_Disparity/Geo-Alberta,', 'Canada/s2p/tests/data/input_pair/../../testoutput/output_pair/tiles/row_0000150_height_350/col_0000150_width_350/pair_1/rectified_ref.tif', '/home/miladg/projects/Stereo_Satellite_Disparity/Geo-Alberta,', 'Canada/s2p/tests/data/input_pair/../../testoutput/output_pair/tiles/row_0000150_height_350/col_0000150_width_350/pair_1/rectified_sec.tif', '/home/miladg/projects/Stereo_Satellite_Disparity/Geo-Alberta,', 'Canada/s2p/tests/data/input_pair/../../testoutput/output_pair/tiles/row_0000150_height_350/col_0000150_width_350/pair_1/rectified_disp.tif']' returned non-zero exit status -6
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/s2p", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.5/dist-packages/s2p/cli.py", line 22, in main
>     s2p.main(user_cfg)
>   File "/usr/local/lib/python3.5/dist-packages/s2p/__init__.py", line 607, in main
>     parallel.launch_calls(stereo_matching, tiles_pairs, nb_workers)
>   File "/usr/local/lib/python3.5/dist-packages/s2p/parallel.py", line 100, in launch_calls
>     outputs.append(r.get(600))  # wait at most 10 min per call
>   File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
>     raise self._value
> subprocess.CalledProcessError: Command '['mgm', '-r', '-16', '-R', '13', '-s', 'vfit', '-t', 'census', '-O', '8', '-confidence_consensusL', '/home/miladg/projects/Stereo_Satellite_Disparity/Geo-Alberta,', 'Canada/s2p/tests/data/input_pair/../../testoutput/output_pair/tiles/row_0000150_height_350/col_0000150_width_350/pair_1/rectified_disp_confidence.tif', '/home/miladg/projects/Stereo_Satellite_Disparity/Geo-Alberta,', 'Canada/s2p/tests/data/input_pair/../../testoutput/output_pair/tiles/row_0000150_height_350/col_0000150_width_350/pair_1/rectified_ref.tif', '/home/miladg/projects/Stereo_Satellite_Disparity/Geo-Alberta,', 'Canada/s2p/tests/data/input_pair/../../testoutput/output_pair/tiles/row_0000150_height_350/col_0000150_width_350/pair_1/rectified_sec.tif', '/home/miladg/projects/Stereo_Satellite_Disparity/Geo-Alberta,', 'Canada/s2p/tests/data/input_pair/../../testoutput/output_pair/tiles/row_0000150_height_350/col_0000150_width_350/pair_1/rectified_disp.tif']' returned non-zero exit status -6

I appreciate your help.

**Comment by gfacciol** [comment]
Hi,
the version in MISS3D is not being maintained, please use
https://github.com/cmla/s2p  instead.
The installation will be much easier too.
Best
-

**Comment by MiladGhorbaniG** [comment]
I had a `conda-py38`, I removed it and also other local pythons, and then reinstalled s2p from `git clone` using [https://github.com/cmla/s2p](https://github.com/cmla/s2p), but it wasn't successful and this error raised again. Then I ran make test. the log was like below:


> collected 30 items                                                             
> 
> tests/block_matching_test.py F.                                          [  6%]
> tests/common_test.py ...                                                 [ 16%]
> tests/end2end_test.py *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> F*** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> F*** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> F*** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> *** stack smashing detected ***: mgm terminated
> F                                               [ 30%]
> tests/estimation_test.py .                                               [ 33%]
> tests/evaluation_test.py ..                                              [ 40%]
> tests/initialization_test.py EEEE                                        [ 53%]
> tests/parallel_test.py .                                                 [ 56%]
> tests/rasterization_test.py .                                            [ 60%]
> tests/rectification_test.py ....                                         [ 73%]
> tests/rpc_utils_test.py ..                                               [ 80%]
> tests/sift_test.py ...                                                   [ 90%]
> tests/triangulation_test.py ...                                          [100%]
> 
> ==================================== ERRORS ====================================
> ________________________ ERROR at setup of test_no_rpc _________________________
>

**Comment by gfacciol** [comment]
You should be able to install also with:  

>  pip3 install s2p 

but first check if the system dependencies are satisfied: 

> sudo apt install libgdal-dev gdal-bin
> sudo apt install build-essential geographiclib-tools libfftw3-dev libgeotiff-dev libtiff5-dev

If the error persists, please submit the new error log in the repository CMLA/s2p.
Best, 
-

**Comment by MiladGhorbaniG** [comment]
I made an [issue](https://github.com/cmla/s2p/issues/61) in the repository CMLA/s2p.
